# Generated by Django 4.2.4 on 2023-11-10 17:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apis", "0002_clients_plans"),
    ]

    operations = [
        migrations.CreateModel(
            name="VDbApi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("site_name", models.TextField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(blank=True, null=True)),
                ("wind_speed_10m_mps", models.FloatField(blank=True, null=True)),
                ("wind_direction_in_deg", models.FloatField(blank=True, null=True)),
                ("temp_c", models.FloatField(blank=True, null=True)),
                ("nowcast_ghi_wpm2", models.FloatField(blank=True, null=True)),
                ("swdown2", models.FloatField(blank=True, null=True)),
                ("cs_data", models.FloatField(blank=True, null=True)),
                ("ci_data", models.FloatField(blank=True, null=True)),
                ("tz", models.TextField(blank=True, null=True)),
                ("ct_data", models.FloatField(blank=True, null=True)),
                ("ct_flag_data", models.TextField(blank=True, null=True)),
                ("forecast_method", models.TextField(blank=True, null=True)),
                ("log_ts", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "v_db_api",
            },
        ),
    ]
